# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

plugins:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - test/dummy/config/environments/*
    - test/dummy/db/schema.rb
    - test/dummy/tmp/**/*


# Layout
Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 200


# Metrics
Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15


# Minitest
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Minitest/SkipWithoutReason:
  Enabled: false


# Packaging
Packaging/BundlerSetupInTests:
  Exclude:
    - test/dummy/config/boot.rb


# Rails
Rails/ActionOrder:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

# The expect method requires Rails 8
Rails/StrongParametersExpect:
  Enabled: false


# Style
Style/ClassAndModuleChildren:
  Exclude:
    - Guardfile

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - db/migrate/*
    - test/dummy/db/migrate/*

Style/StringConcatenation:
  Exclude:
    - test/test_helper.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes
