require 'minimalist_authentication/engine'
require 'minimalist_authentication/user'
require 'minimalist_authentication/null_password'
require 'minimalist_authentication/controller'
require 'minimalist_authentication/sessions'
require 'minimalist_authentication/test_helper'
